name: Promote API

on:
  workflow_call:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        type: string
        required: true

jobs:
  publish-api:
    runs-on: ubuntu-latest

    env:
      LOCATIONS_REGISTRY_URL: http://localhost:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug
        run: |
          echo "OpenAPI Spec: ${{ inputs.openapi_spec }}"

      - name: Get server from spec
        id: get-server
        run: |
          echo "::set-output name=server::$(yq eval '.servers[0].url' ${{ inputs.openapi_spec }})"

      - name: Fetch upstreams from $LOCATIONS_REGISTRY_URL for ${{ steps.get-server.outputs.server }}
        id: fetch-locations
        run: |
          curl -s "$LOCATIONS_REGISTRY_URL/locations?mock_url=${{ steps.get-server.outputs.server }}" | jq .[0] > locations.json

          # Check examples/locations.json for resulting file
          cat locations.json

      - name: Generate Kong upstreams definitions
        id: generate-upstreams
        run: |
          #!/bin/bash
          set -e

          # Read locations.json and extract upstreams array
          upstreams=$(jq -c '.upstreams' locations.json)

          # Create a new yaml file with upstreams
          echo "upstreams:" > upstreams.yaml
          echo "$upstreams" | jq -r '.[] | "  - name: \(.name)\n    targets:\n     - target: \(.target)"' >> upstreams.yaml
          
          # Check examples/upstreams.yaml for resulting file
          cat upstreams.yaml

      - name: Prepare plugins
        id: prepare-plugins
        run: |
          #!/bin/bash
          set -e

          # Read locations.json and extract upstreams array
          upstreams=$(jq -c '.upstreams' locations.json)

          # Generate route-by-header plugin rules array based on available upstreams
          rules=$(echo "$upstreams" | jq -c '[.[] | {condition: {location: .location}, upstream_name: .name}]')

          # Update route-by-header plugin with generated rules
          jq --argjson rules "$rules" \
            '.["add-plugins"][0].plugins |= map(if .name == "route-by-header" then .config.rules = $rules else . end)' \
            plugins/plugins.json > plugins.json

          # Check examples/plugins.json for resulting file
          cat plugins.json

      - name: Deck Ops
        id: deck-ops
        run: |
            #!/bin/bash
            set -e
            
            FIRST_UPSTREAM=$(jq -r '.upstreams[0].name' locations.json)

            echo "Converting OpenAPI to Kong"
            cat openapi.yaml | deck file openapi2kong -o kong.yaml
            cat kong.yaml

            echo "Merging Upstreams to Kong state file"
            deck file merge kong.yaml upstreams.yaml -o kong.yaml
            cat kong.yaml

            echo "Adding Plugins to Kong state file"
            cat kong.yaml | deck file add-plugins plugins.json -o kong.yaml
            cat kong.yaml

            echo "Patching Service host to $FIRST_UPSTREAM"
            cat kong.yaml | deck file patch --selector="$..services[0]" --value='host:"'$FIRST_UPSTREAM'"' -o kong.yaml
            cat kong.yaml

            echo "Adding location based paths to Kong state file"
            yq eval -i '
            .services[].routes[].paths |= . + map(sub("^~", "~/(?<location>eu|us|ch)"))
            ' kong.yaml

            # Check examples/kong.yaml for resulting file
            cat kong.yaml

      - name: Validate Kong state file
        id: validate-kong-state
        run: |
          deck file validate kong.yaml

      - name: Sync Kong state file
        id: sync-kong-state
        run: |
          deck gateway sync kong.yaml

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            upstreams.yaml
            plugins.json
            kong.yaml
            locations.json